language: c
compiler:
  - gcc
  - clang


script:
  - docker version
  - docker build -t local/r-base r-base
  - docker run local/r-base r -e 'sapply(installed.packages()[,"Package"], tools::testInstalledPackage)'
